create table balance (id int8 not null, amount float8, client_id int8 not null, org_bonus_id int8 not null, primary key (id));
create table balance_history (id int8 not null, amount float8, created_date timestamp, operation_type varchar(255), balance_id int8 not null, primary key (id));
create table client (id int8 not null, sex varchar(255), created_date timestamp, first_name varchar(255), last_name varchar(255), locale char(1), nationality varchar(255), patronymic varchar(255), personal_code varchar(255), primary key (id));
create table client_device (id int8 not null, client_locale varchar(255), imei varchar(255), last_enter_date timestamp, password varchar(255), phone_number varchar(255), status boolean default true, client_id int8 not null, primary key (id));
create table client_event (id int8 not null, created_date timestamp, notification_date timestamp, client_id int8 not null, event_id int8 not null, primary key (id));
create table client_organization (client_id int8 not null, organization_id int8 not null, primary key (client_id, organization_id));
create table client_preference_value (id int8 not null, value int4, client_id int8 not null, organization_id int8 not null, organization_preference_category_id int8 not null, primary key (id));
create table event (id int8 not null, created_date timestamp, date_from timestamp, date_to timestamp, description varchar(255), organization_id int8 not null, primary key (id));
create table filial (id int8 not null, address varchar(255), average_rate float8, created_date timestamp, description varchar(255), latitude float8, longitude float8, name varchar(255), status boolean default true, organization_id int8 not null, primary key (id));
create table filial_rate (id int8 not null, comment varchar(255), created_date timestamp, rate float8, client_id int8 not null, filial_id int8 not null, organization_id int8 not null, primary key (id));
create table org_bonus (id int8 not null, created_date timestamp, deleted_date timestamp, status boolean default true, valid_from timestamp, valid_to timestamp, validity int4, org_bonus_type_id int8 not null, organization_id int8 not null, primary key (id));
create table org_bonus_type (id int8 not null, name varchar(255), value_type varchar(255), primary key (id));
create table org_bonus_value (id int8 not null, max int4, min int4, value int4, org_bonus_id int8 not null, primary key (id));
create table org_category (id int8 not null, created_date timestamp, description varchar(255), image_url varchar(255), name varchar(255), primary key (id));
create table org_category_tag (org_category_id int8 not null, tag_id int8 not null, primary key (org_category_id, tag_id));
create table org_preference_category (id int8 not null, organization_id int8 not null, preference_category_id int8 not null, primary key (id));
create table organization (id int8 not null, created_date timestamp, description varchar(255), image_url varchar(255), name varchar(255), status boolean default true, category_id int8 not null, primary key (id));
create table preference_category (id int8 not null, name varchar(255), type varchar(255), parent_id int8 not null, primary key (id));
create table role (id int8 not null, description varchar(255), name varchar(255), primary key (id));
create table tag (id int8 not null, name varchar(255), primary key (id));
create table users (id int8 not null, create_date timestamp, password varchar(255) not null, status varchar(255), username varchar(255) not null, organization_id int8 not null, role_id int8 not null, primary key (id));
create sequence balance_history_seq start 1 increment 1;
create sequence balance_seq start 1 increment 1;
create sequence category_tag_seq start 1 increment 1;
create sequence client_device_seq start 1 increment 1;
create sequence client_event_seq start 1 increment 1;
create sequence client_pref_value_seq start 1 increment 1;
create sequence client_seq start 1 increment 1;
create sequence event_seq start 1 increment 1;
create sequence filial_rate_seq start 1 increment 1;
create sequence filial_seq start 1 increment 1;
create sequence org_bonus_seq start 1 increment 1;
create sequence org_bonus_type_seq start 1 increment 1;
create sequence org_bonus_value_seq start 1 increment 1;
create sequence org_category_seq start 1 increment 1;
create sequence org_preference_category_seq start 1 increment 1;
create sequence organization_seq start 1 increment 1;
create sequence preference_category_seq start 1 increment 1;
create sequence role_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
alter table if exists org_bonus add constraint UK_ijc69x6w7ait7e2k2l02scvew unique (org_bonus_type_id);
alter table if exists org_bonus_value add constraint UK_q2sd4hi85vm4lodfbxrt0wrd unique (org_bonus_id);
alter table if exists balance add constraint FK13o20b873igddbreehug3mxu1 foreign key (client_id) references client;
alter table if exists balance add constraint FKpvfx3lcdihne27fw4vtsfq3uo foreign key (org_bonus_id) references org_bonus;
alter table if exists balance_history add constraint FKh7q28d940m7fkjxasp9fx4cdn foreign key (balance_id) references balance;
alter table if exists client_device add constraint FK5sdhnyeog1gce5acnqpse1bxk foreign key (client_id) references client;
alter table if exists client_event add constraint FK7y6ctrgn2ovkor7ceqa5vlchv foreign key (client_id) references client;
alter table if exists client_event add constraint FKdpm598tqq3wl1fg99obb2wngu foreign key (event_id) references event;
alter table if exists client_organization add constraint FKmebdjayaenowkol0cr6pvhuc8 foreign key (organization_id) references organization;
alter table if exists client_organization add constraint FKtfjeemig9tda2mh2h6a9rngua foreign key (client_id) references client;
alter table if exists client_preference_value add constraint FKi021nym7dx376dgutwg5t75kr foreign key (client_id) references client;
alter table if exists client_preference_value add constraint FKrdajbxkkt1pdtbx1i2k2tcjvh foreign key (organization_id) references organization;
alter table if exists client_preference_value add constraint FKl9aho0mn00grbmxkb3jwvmv5f foreign key (organization_preference_category_id) references org_preference_category;
alter table if exists event add constraint FKkarqc3c84scr3r5ncv5stqbk2 foreign key (organization_id) references organization;
alter table if exists filial add constraint FKs5mv6448op5xhdklmeuwpvlb foreign key (organization_id) references organization;
alter table if exists filial_rate add constraint FKhv9jm6wrdc6hab2b70k2br1dw foreign key (client_id) references client;
alter table if exists filial_rate add constraint FK6bbp1pfbl725jmpm68r6jlge1 foreign key (filial_id) references filial;
alter table if exists filial_rate add constraint FK24rgd72um9941ihv4m63x92k9 foreign key (organization_id) references organization;
alter table if exists org_bonus add constraint FKq2d3j7lic0k2d22xqqn2xchxv foreign key (org_bonus_type_id) references org_bonus_type;
alter table if exists org_bonus add constraint FKiuc9fpdvejj7umioyt82lu0pn foreign key (organization_id) references organization;
alter table if exists org_bonus_value add constraint FKeqjrbt7i4wvd36jmchbl6yswv foreign key (org_bonus_id) references org_bonus;
alter table if exists org_category_tag add constraint FKgre9prww05l4itxblcyderxbf foreign key (tag_id) references tag;
alter table if exists org_category_tag add constraint FKs7uiqrfp6nea1d6orry6v0kgs foreign key (org_category_id) references org_category;
alter table if exists org_preference_category add constraint FK8eg9mv80rubimvoocrjeli6aj foreign key (organization_id) references organization;
alter table if exists org_preference_category add constraint FK3ioe6em34siocwplvumnpj6jd foreign key (preference_category_id) references preference_category;
alter table if exists organization add constraint FKga36rgp1bkw38qy2uplshwhql foreign key (category_id) references org_category;
alter table if exists preference_category add constraint FKtdv8rj2d2yvqqjmmu715ajc6s foreign key (parent_id) references preference_category;
alter table if exists users add constraint FK9q8fdenwsqjwrjfivd5ovv5k3 foreign key (organization_id) references organization;
alter table if exists users add constraint FK4qu1gr772nnf6ve5af002rwya foreign key (role_id) references role;
